### ISSUE TITLE
Pose Information never retrieved?

### ISSUE THREAD

**Issue by iamsavva** [ANYbotics/elevation_mapping#142]
ahoy! 

i'm running D435i on a TX2. I'm using VINS-Fusion-GPU as my VIO to get pose estimates: VIO pubilshes a nav_msg, I republish it as a stamped pose with cov, feed it into the elevation mapping, but for some reason it doesn't seem to be recognized. Could you help me with that, please?

Here are the errors and the debug messages I'm getting:

![elevation_debug](https://user-images.githubusercontent.com/62255121/98195254-45ae4d00-1eef-11eb-8b60-5ae1becb571d.png)

and here are the setup messages:
![start_debug](https://user-images.githubusercontent.com/62255121/98195498-ea308f00-1eef-11eb-8c41-1c85550154ec.png)

Here's the yaml that I'm running:
```
input_sources:
- name: front # A name to identify the input source
  type: pointcloud # Supported types: pointcloud
  topic: /camera/depth/color/points
  queue_size: 5
  publish_on_update: true # Wheter to publish the elevation map after a callback from this source. 

map_frame_id: body
robot_base_frame_id: body
track_point_frame_id: body
sensor_frame_id: camera_depth_optical_frame

robot_pose_topic: /util_node/util/pose
robot_pose_cache_size: 200
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
time_tolerance: 1

robot_pose_cache_size: 10
```

Here's my tf_tree:

![elevation_tree](https://user-images.githubusercontent.com/62255121/98195302-69719300-1eef-11eb-8b82-1a6798601d25.png)

would appreciate any help!
Cheers,
Savva M
