### ISSUE TITLE
D435i issue

### ISSUE THREAD

**Issue by kiwi-sherbet** [ANYbotics/elevation_mapping#155]
Hi, I would like to use `elevation _mapping` package with Realsense d435i. When I ran it, I got the following error messages.

`Parameter 'point_cloud_topic' is deprecated, please use 'input_sources' instead`

It seems that the configuration for the parameter `input_sources` is not set properly, and I also found the related terms in the readme file. But, I do not know how I can change `input_sources` parameter. Where can I set up the configuration for it?

Thanks!

**Comment by maximilianwulf** [comment]
Hey @kiwi-sherbet, 

you can configure `input_source` with : 

```
input_sources:
  front: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
```

**Comment by kiwi-sherbet** [comment]
Thank you for answer!

Where (in what file) can I change the lines for configuration?

**Comment by maximilianwulf** [comment]
Hi @kiwi-sherbet, you can add these changes to your configuration yaml file.

**Comment by kiwi-sherbet** [comment]
Thank you for reply!
Still, I get an error that "Could not configure input source front because no sensor_processor was given." It seems that I am missing some configuration setups.
If there is any demo or example for D435i, can I ask for it? It would be great help!

**Comment by maximilianwulf** [comment]
Sorry, forgot that. You also have to add the sensor processor, like: 

```
input_sources:
 camera: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /your_topic # your topic
    queue_size: 1
    publish_on_update: true
    sensor_processor: 
      ignore_points_above: .inf
      ignore_points_below: -.inf
      cutoff_min_depth: 0.1
      cutoff_max_depth: 1.5
      type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
      normal_factor_a: 0.001063
      normal_factor_b:  0.003949
      normal_factor_c: 0.0
      normal_factor_d: 0.0008278
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg
```
