### ISSUE TITLE
Elevation mapping crashes when StereoSensorProcessor is used

### ISSUE THREAD

**Issue by ercanburak** [ANYbotics/elevation_mapping#164]
Hi, and thanks for your work.

I'm trying to use elevation mapping node with point cloud generated by a ZED2 camera, so I adjust the input sources like below in my yaml file:

```yaml
input_sources:
    zed:
        type: pointcloud
        topic: /zed2/zed_node/point_cloud/cloud_registered
        queue_size: 1
        publish_on_update: true
        sensor_processor:
            type: stereo
            ignore_points_above:       1.4
            apply_voxelgrid_filter:    true
            voxelgrid_filter_size:     0.1
            p_1:   0.03287  # from aslam
            p_2:  -0.0001276 # from aslam
            p_3:   0.4850 # from aslam
            p_4: 399.1046 # from aslam
            p_5:   0.000006735 # from aslam
            lateral_factor: 0.001376915 # from aslam
            depth_to_disparity_factor: 47.3 # from aslam
            cutoff_min_depth:          0.3
            cutoff_max_depth:          20
```

When the `type` of `sensor_processor` is `stereo`, the elevation mapping node crashes when `computeVariances` method of `StereoSensorProcessor` is called. This is probably occuring since `computeVariances` call `getI` and `getJ` methods, where an unitialized vector named `indices_` is trying to be accessed.
