### ISSUE TITLE
receiving pointclouds from realsense d400

### ISSUE THREAD

**Issue by rolandgvc** [ANYbotics/elevation_mapping#175]
Hi! I'm a bit confused about visualizing the elevation maps with the pointcloud generated by my realsense camera (d455). Here is my current configuration:

**realsense_demo.launch**
```
<launch>

  <!-- Elevation mapping node -->
  <node pkg="elevation_mapping" type="elevation_mapping" name="elevation_mapping" output="screen">
    <rosparam command="load" file="$(find elevation_mapping_demos)/config/robots/d455.yaml" />
        <rosparam command="load" file="$(find elevation_mapping_demos)/config/elevation_maps/simple_demo_map.yaml" />
    <rosparam command="load" file="$(find elevation_mapping_demos)/config/postprocessing/postprocessor_pipeline.yaml" />
  </node>

  <!-- Launch visualizations for the resulting elevation map -->
  <include file="$(find elevation_mapping_demos)/launch/visualization.launch" />

  <!-- Launch RViz with the demo configuration -->
  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find elevation_mapping_demos)/rviz/elevation_map_visualization_pointcloud.rviz" />

</launch>
```

**d455.yaml**
```
input_sources:
  camera:
    type: pointcloud
    topic: "/camera/depth_registered/points"
    queue_size: 1
    publish_on_update: true
    sensor_processor: 
      ignore_points_above: .inf
      ignore_points_below: -.inf
      cutoff_min_depth: 0.1
      cutoff_max_depth: 1.5
      type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
      normal_factor_a: 0.001063
      normal_factor_b:  0.003949
      normal_factor_c: 0.0
      normal_factor_d: 0.0008278
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg

map_frame_id: "odom"
robot_base_frame_id: "camera_link"
robot_pose_with_covariance_topic: "/pose"
robot_pose_cache_size: 200
track_point_frame_id: "base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
```

**rviz**
![Screenshot from 2021-07-19 19-22-31](https://user-images.githubusercontent.com/26813782/126208611-f5ff8398-693b-4c16-9584-079befb28a2c.png)

**rqt_graph**
![Screenshot from 2021-07-19 19-21-42](https://user-images.githubusercontent.com/26813782/126208558-59072240-6d17-47d7-bf57-a6a1abcba9c5.png)

At the launch of `elevation_mapping` node, I'm getting these errors as well:
![Screenshot from 2021-07-19 19-29-01](https://user-images.githubusercontent.com/26813782/126209118-948c024c-0a85-48b8-aa0a-a049c046b098.png)

Please let me know if I'm doing something wrong or the next steps for visualizing the maps. Thanks!
