### ISSUE TITLE
Postprocessor Pipeline with SlidingWindow: no default buffer start index.

### ISSUE THREAD

**Issue by Max-Ole** [ANYbotics/elevation_mapping#190]
Hello, not sure whether to ask here or at the grid_map page.

I was using the post-processing feature and then tried to add a `SlidingWindowMathExpressionFilter`. This however results in this error as soon as the robot is moved or a map is loaded:
`Postprocessor pipeline, thread 0 experienced an error: SlidingWindowIterator cannot be used with grid maps that don't have a default buffer start index.`

Is there an option anywhere to set the default buffer start index? I am not interacting with the map or package programmatically, only through the launch file and referenced yaml files.

I also tried to use a DuplicationFilter in case the SlidingWindowMathExpressionFilter can't create  a new layer. This did not seem to change anything. Here is part of the yaml file for the postprocessor pipeline:
```
postprocessor_pipeline:
  # [ ... ]

  # Duplicate a layer to get a default buffer start index. (fix attempt)
   - name: duplicate_3
     type: gridMapFilters/DuplicationFilter
     params:
       input_layer: elevation
       output_layer: output

  # get height of edge
   - name: math_expression
     type: gridMapFilters/SlidingWindowMathExpressionFilter
     params:
       input_layer: elevation
       output_layer: output
       expression: meanOfFinites(elevation) # Box blur from example to test/debug this filter
       # expression: max(elevation) - min(elevation) # planned use: get height of edge as max height difference in region around edge
       compute_empty_cells: false
       edge_handling: crop # options: inside, crop, empty, mean
       window_size: 5 # in number of cells
```
