### ISSUE TITLE
Questions about the Realsense D455 Demo

### ISSUE THREAD

**Issue by zhanghua7099** [ANYbotics/elevation_mapping#192]
Hi! 

I encountered the same error as this closed [issue](https://github.com/ANYbotics/elevation_mapping/issues/175#issuecomment-883311092).

Could you please help me to fix this bug? The author seems to solve this problem. But I can't understand his [method](https://github.com/ANYbotics/elevation_mapping/issues/175#issuecomment-884046441).

**Comment by maximilianwulf** [comment]
Hi @zhanghua7099 can you share your configuration?

**Comment by zhanghua7099** [comment]
My configuration file is as the same as the closed issue. 

Ubuntu 20.04+Ros noetic

realsense_demo.launch
```
<launch>

  <!-- Elevation mapping node -->
  <node pkg="elevation_mapping" type="elevation_mapping" name="elevation_mapping" output="screen">
    <rosparam command="load" file="$(find elevation_mapping_demos)/config/elevation_maps/simple_demo_map.yaml" />
    <rosparam command="load" file="$(find elevation_mapping_demos)/config/robots/d455.yaml" />
    <rosparam command="load" file="$(find elevation_mapping_demos)/config/postprocessing/postprocessor_pipeline.yaml" />  
  </node>

  <!-- Launch visualizations for the resulting elevation map -->
  <include file="$(find elevation_mapping_demos)/launch/visualization.launch" />

  <!-- Launch RViz with the demo configuration -->
  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find elevation_mapping_demos)/rviz/elevation_map_visualization_pointcloud.rviz" />

</launch>
```
d455.yaml
```
input_sources:
  camera:
    type: pointcloud
    topic: "/camera/depth/color/points"
    queue_size: 1
    publish_on_update: true
    sensor_processor: 
      ignore_points_above: .inf
      ignore_points_below: -.inf
      cutoff_min_depth: 0.1
      cutoff_max_depth: 1.5
      type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
      normal_factor_a: 0.001063
      normal_factor_b:  0.003949
      normal_factor_c: 0.0
      normal_factor_d: 0.0008278
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg

map_frame_id: "odom"
robot_base_frame_id: "camera_link"
robot_pose_with_covariance_topic: "/pose"
robot_pose_cache_size: 200
track_point_frame_id: "base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
```
rqt_graph
![2021-12-01 13-53-25 的屏幕截图](https://user-images.githubusercontent.com/28104987/144179763-749a6ec1-0352-40e1-ad69-41fe399e5eff.png)

elevation mapping console
![2021-12-01 13-56-14 的屏幕截图](https://user-images.githubusercontent.com/28104987/144179875-d3ddfbdc-d07e-4fc8-8e64-559e5e08ea49.png)
