### ISSUE TITLE
Realsense D455 Demo

### ISSUE THREAD

**Issue by aleio1** [ANYbotics/elevation_mapping#237]
I am trying to obtain an elevation map using my Realsense D455 but probably I am missing something.

I launch **realsense_demo.launch** using the following command:

**roslaunch elevation_mapping_demos realsense_demo.launch**

```
<launch>

  <!-- Elevation mapping node -->
  <node pkg="elevation_mapping" type="elevation_mapping" name="elevation_mapping" output="screen">
    <rosparam command="load" file="$(find elevation_mapping_demos)/config/robots/d455.yaml" />
        <rosparam command="load" file="$(find elevation_mapping_demos)/config/elevation_maps/simple_demo_map.yaml" />
    <rosparam command="load" file="$(find elevation_mapping_demos)/config/postprocessing/postprocessor_pipeline.yaml" />
  </node>

  <!-- Launch visualizations for the resulting elevation map -->
  <include file="$(find elevation_mapping_demos)/launch/visualization.launch" />

  <!-- Launch RViz with the demo configuration -->
  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find elevation_mapping_demos)/rviz/elevation_map_visualization_pointcloud.rviz" />

</launch>
```

**d455.yaml**

```
input_sources:
  camera:
    type: pointcloud
    topic: "/camera/depth_registered/points"
    queue_size: 1
    publish_on_update: true
    sensor_processor: 
      ignore_points_above: .inf
      ignore_points_below: -.inf
      cutoff_min_depth: 0.1
      cutoff_max_depth: 1.5
      type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
      normal_factor_a: 0.001063
      normal_factor_b:  0.003949
      normal_factor_c: 0.0
      normal_factor_d: 0.0008278
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg

map_frame_id: "odom" #i tried also to change it to "camera_link"
robot_base_frame_id: "camera_link"
robot_pose_with_covariance_topic: "/pose"
robot_pose_cache_size: 200
track_point_frame_id: "base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
```

and then I launch realsense node in order to obtain pointcloud using 

**roslaunch realsense2_camera rs_rgbd.launch** (or **roslaunch realsense2_camera rs_camera.launch filters:=pointcloud**)

but I am not able to see the elevation map. Sometimes I get some errors about frames and tfs that I don't know how to fix.

Could you give me some hints?
