### ISSUE TITLE
Multiple input sources

### ISSUE THREAD

**Issue by martinlucan** [ANYbotics/elevation_mapping#265]
Hi there, 
I intend to use 3 depth cameras, one of them publishes a point cloud with ~ 30 hz, while the rest is ~ 13 hz. I use following configuration:

```
input_sources:
  camera_1: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /camera_1/point_cloud
    queue_size: 1
    publish_on_update: false # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
      cutoff_min_depth: 0.5
      cutoff_max_depth: 3.0
  camera_2: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /camera_2/points
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
      cutoff_min_depth: 0.3
      cutoff_max_depth: 2.0
  camera_3: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /camera_3/points
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
      cutoff_min_depth: 0.3
      cutoff_max_depth: 2.0
map_frame_id: "map"
robot_base_frame_id: "robot_1_ground_truth/body"
fused_map_publishing_rate: 10.0
robot_pose_with_covariance_topic: /pose_cov # Leaving this empty skips pose covariance updates.
robot_pose_cache_size: 200
track_point_frame_id: "robot_1_ground_truth/body"
```
Although I see the error complaining about a timestamp discrepancy. From my point of view, the difference between the requested update and the last update is fairly small. Is there any configuration tweak that would work this out? I guess, the map should be published in a callback to a source with lower frequency.

```
[ERROR] [1720186451.564462530]: Updating process noise failed.
[ERROR] [1720186451.588190906]: Requested update with time stamp 1720186451.477186, but time of last update was 1720186451.481820.
```
